/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prFinal;

import java.io.File;

/**
 * Clase que hereda de InternalFrame. Graba el sonido recibido por el micrófono del pc.
 * 
 * @author Roberto
 */
public class GrabadorInterno extends javax.swing.JInternalFrame {

    SMRecorder grabador;
    /**
     * Creates new form GrabadorInterno
     */
    public GrabadorInterno(File f) {

        initComponents();
        
        grabador = new SMSoundRecorder(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grabar = new javax.swing.ButtonGroup();
        panelRec = new javax.swing.JPanel();
        BotonRec = new javax.swing.JToggleButton();
        BotonStop = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Grabador");
        setMaximumSize(new java.awt.Dimension(210, 98));
        setMinimumSize(new java.awt.Dimension(210, 98));
        setVisible(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelRec.setLayout(new javax.swing.BoxLayout(panelRec, javax.swing.BoxLayout.LINE_AXIS));

        Grabar.add(BotonRec);
        BotonRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/RecordPressed_48x48.png"))); // NOI18N
        BotonRec.setMaximumSize(new java.awt.Dimension(100, 65));
        BotonRec.setMinimumSize(new java.awt.Dimension(100, 65));
        BotonRec.setPreferredSize(new java.awt.Dimension(100, 65));
        BotonRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRecActionPerformed(evt);
            }
        });
        panelRec.add(BotonRec);

        Grabar.add(BotonStop);
        BotonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/StopDisabled_48x48.png"))); // NOI18N
        BotonStop.setMaximumSize(new java.awt.Dimension(100, 65));
        BotonStop.setMinimumSize(new java.awt.Dimension(100, 65));
        BotonStop.setPreferredSize(new java.awt.Dimension(100, 65));
        BotonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonStopActionPerformed(evt);
            }
        });
        panelRec.add(BotonStop);

        getContentPane().add(panelRec);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRecActionPerformed
        if(grabador != null){
            grabador.record();
            BotonRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFianl/RecordDisabled_48x48.png")));
            BotonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/StopNormalRed_48x48.png")));
        }
    }//GEN-LAST:event_BotonRecActionPerformed

    private void BotonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonStopActionPerformed
        if(grabador != null){
            grabador.stop();
            BotonRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/RecordPressed_48x48.png")));
            BotonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/StopDisabled_48x48.png")));
        }
    }//GEN-LAST:event_BotonStopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonRec;
    private javax.swing.JToggleButton BotonStop;
    private javax.swing.ButtonGroup Grabar;
    private javax.swing.JPanel panelRec;
    // End of variables declaration//GEN-END:variables
}
