/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prFinal;

import java.io.*;

/**
 * Clase que hereda de InternalFrame y reproduce un audio pasado como argumento por el constructor
 * 
 * @author Roberto
 */
public class ReproductorInterno extends javax.swing.JInternalFrame {
   
    SMPlayer player;
    /**
     * Creates new form ReproductorInterno
     */
    public ReproductorInterno(File f) {

        initComponents();
        player = new SMClipPlayer(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reproducir = new javax.swing.ButtonGroup();
        panelRepr = new javax.swing.JPanel();
        BotonPlay = new javax.swing.JToggleButton();
        BotonStop = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Reproductor");
        setMaximumSize(new java.awt.Dimension(210, 98));
        setMinimumSize(new java.awt.Dimension(210, 98));
        setVisible(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelRepr.setLayout(new javax.swing.BoxLayout(panelRepr, javax.swing.BoxLayout.LINE_AXIS));

        Reproducir.add(BotonPlay);
        BotonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/PlayPressed_48x48.png"))); // NOI18N
        BotonPlay.setMaximumSize(new java.awt.Dimension(100, 65));
        BotonPlay.setMinimumSize(new java.awt.Dimension(100, 65));
        BotonPlay.setPreferredSize(new java.awt.Dimension(100, 65));
        BotonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPlayActionPerformed(evt);
            }
        });
        panelRepr.add(BotonPlay);

        Reproducir.add(BotonStop);
        BotonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/StopDisabled_48x48.png"))); // NOI18N
        BotonStop.setMaximumSize(new java.awt.Dimension(100, 65));
        BotonStop.setMinimumSize(new java.awt.Dimension(100, 65));
        BotonStop.setPreferredSize(new java.awt.Dimension(100, 65));
        BotonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonStopActionPerformed(evt);
            }
        });
        panelRepr.add(BotonStop);

        getContentPane().add(panelRepr);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPlayActionPerformed
        if(player != null){
            
            player.play();
            BotonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/PlayDisabled_48x48.png")));
            BotonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/StopPessedBlue_48x48.png")));
        }
    }//GEN-LAST:event_BotonPlayActionPerformed

    private void BotonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonStopActionPerformed
        if(player!=null){
            
            player.stop();
            BotonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/PlayPressed_48x48.png")));
            BotonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prFinal/StopDisabled_48x48.png")));
        }
    }//GEN-LAST:event_BotonStopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonPlay;
    private javax.swing.JToggleButton BotonStop;
    private javax.swing.ButtonGroup Reproducir;
    private javax.swing.JPanel panelRepr;
    // End of variables declaration//GEN-END:variables
}
