/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prFinal;

import java.awt.*;
import javax.swing.*;

/**
 * Clase que hereda de InternalFrame y hace de puente entre el frame principal
 * y la clase lienzoImagen donde se visualizan y modifican imágenes
 * 
 * @author Roberto
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    JFramePrFinal parent;
    LienzoImagen li;
    public VentanaInterna(JFramePrFinal parent) {
        initComponents();
        this.parent = parent;
        
        this.setSize(300, 300);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        
        LienzoImagen lienzo = new LienzoImagen(parent);
        li = lienzo;
        Scroll.setVisible(true);
        Scroll.setViewportView(lienzo);
        lienzo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lienzo");
        setMinimumSize(new java.awt.Dimension(100, 100));
        setNormalBounds(new java.awt.Rectangle(0, 0, 200, 200));
        setPreferredSize(new java.awt.Dimension(200, 200));
        setVisible(true);

        Scroll.setAutoscrolls(true);
        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    // End of variables declaration//GEN-END:variables

    /*public static void main(String[] args) {
        JInternalFrame miframe = new VentanaInterna(null);
	miframe.setVisible(true);
    }*/
    
    public LienzoImagen getLienzo(){
        return li;
    }
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
