/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prFinal;

import java.awt.Component;
import java.io.*;
import javax.media.*;

/**
 * Clase que hereda de InternalFrame y reproduce un vídeo pasado por parámetro al constructor de clase
 * 
 * @author Roberto
 */
public class VentanaInternaJMFPlayer extends javax.swing.JInternalFrame {
    //private VentanaInternaJMFPlayer ventana = null;
    private Player player = null;
    private Component areaVisual = null;
    private Component panelControl = null;
    /**
     * Creates new form VentanaInternaJMFPlayer
     * @param f
     */
    public VentanaInternaJMFPlayer(File f) {
        try {
            MediaLocator ml = new MediaLocator(f.toURI().toURL());
            //System.out.println(f.toURI().toURL());
            player = Manager.createRealizedPlayer(ml);
        } catch(IOException | CannotRealizeException | NoPlayerException e) {
            System.err.println("No se pudo cargar el localizador de medios");
        }
        initComponents();
        jPanelVisualizacion.setVisible(true);
        jPanelControl.setVisible(true);
        
        if(player != null){
            areaVisual = player.getVisualComponent();
            if(areaVisual != null)
                jPanelVisualizacion.add(areaVisual);

            panelControl = player.getControlPanelComponent();
            if(panelControl != null)
                jPanelControl.add(panelControl);
        }
        
        this.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVisualizacion = new javax.swing.JPanel();
        jPanelControl = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reproductor");
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(210, 98));
        setPreferredSize(new java.awt.Dimension(510, 398));
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanelVisualizacion.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanelVisualizacion.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelVisualizacion, java.awt.BorderLayout.CENTER);

        jPanelControl.setPreferredSize(new java.awt.Dimension(800, 20));
        jPanelControl.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelControl, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        this.close();
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelVisualizacion;
    // End of variables declaration//GEN-END:variables

    private void play(){
        player.start();
    }
    
    private void close(){
        player.close();
    }
}
